function [NEW_RADAR_DATA] = Reshape_Data(filename,ADC_SAMPLE,TX_NUM,CHIRP_NUM,FRAME_LENGTH)
%% 加载数据并重排为ADC_SAMPLE*TX_NUM*CHIRP_NUM*FRAME_LENGTH
%% BY YUXULIANG,ZJU,20211101

    [data] = readDCA1000(filename);
    INIT_FRAME = 1;
    FRAME_NUM = 20;
    %% 重排数据
    NEW_RX1_DATA = reshape(data(1,:),ADC_SAMPLE,TX_NUM,CHIRP_NUM,FRAME_LENGTH);
    NEW_RX2_DATA = reshape(data(2,:),ADC_SAMPLE,TX_NUM,CHIRP_NUM,FRAME_LENGTH);
    NEW_RX3_DATA = reshape(data(3,:),ADC_SAMPLE,TX_NUM,CHIRP_NUM,FRAME_LENGTH);
    NEW_RX4_DATA = reshape(data(4,:),ADC_SAMPLE,TX_NUM,CHIRP_NUM,FRAME_LENGTH);
    RADAR_DATA = cat(2,NEW_RX1_DATA,NEW_RX2_DATA,NEW_RX3_DATA,NEW_RX4_DATA); % 获取重排后数据
    NEW_RADAR_DATA = RADAR_DATA(:,:,:,INIT_FRAME:INIT_FRAME+FRAME_NUM-1);
    RADAR_DATA_SIZE = size(NEW_RADAR_DATA);

end
